"""PDF conversion service using LibreOffice headless."""

import logging
import os
import subprocess
import tempfile
import uuid

from app.core.config import settings

logger = logging.getLogger(__name__)


def convert_docx_to_pdf(docx_bytes: bytes) -> bytes:
    """Convert DOCX bytes to PDF using LibreOffice headless."""
    tmp_dir = tempfile.mkdtemp()
    docx_path = os.path.join(tmp_dir, f"{uuid.uuid4().hex}.docx")
    pdf_path = docx_path.replace(".docx", ".pdf")

    try:
        with open(docx_path, "wb") as f:
            f.write(docx_bytes)

        cmd = [
            settings.LIBREOFFICE_PATH,
            "--headless",
            "--convert-to",
            "pdf",
            "--outdir",
            tmp_dir,
            docx_path,
        ]

        result = subprocess.run(
            cmd,
            capture_output=True,
            text=True,
            timeout=120,
        )

        if result.returncode != 0:
            logger.error(f"LibreOffice conversion failed: {result.stderr}")
            raise RuntimeError(f"PDF conversion failed: {result.stderr}")

        if not os.path.exists(pdf_path):
            generated = [f for f in os.listdir(tmp_dir) if f.endswith(".pdf")]
            if generated:
                pdf_path = os.path.join(tmp_dir, generated[0])
            else:
                raise RuntimeError("PDF file not generated by LibreOffice")

        with open(pdf_path, "rb") as f:
            return f.read()
    finally:
        for fname in os.listdir(tmp_dir):
            try:
                os.remove(os.path.join(tmp_dir, fname))
            except OSError:
                pass
        try:
            os.rmdir(tmp_dir)
        except OSError:
            pass
